export const CHANGE_MENU_STATE = 'CHANGE_MENU_STATE';
export const SET_MENU_STATE = 'SET_MENU_STATE';
export const CHANGE_MENU_INFO_STATE = 'CHANGE_MENU_INFO_STATE';
export const SET_MENU_INFO_STATE = 'SET_MENU_INFO_STATE';
