export enum MenuStateEnum {
  NONE = 'NONE',
  MOVING_ACTIVE = 'MOVING_ACTIVE',
  MOVING_DEACTIVE = 'MOVING_DEACTIVE',
  MOVING_OVER_ACTIVE = 'MOVING_OVER_ACTIVE',
  MOVING_OVER_DEACTIVE = 'MOVING_OVER_DEACTIVE',
  MOVING_OVER_WITH_SIDE_BAR_ACTIVE = 'MOVING_OVER_WITH_SIDE_BAR_ACTIVE',
  MOVING_OVER_WITH_SIDE_BAR_DEACTIVE = 'MOVING_OVER_WITH_SIDE_BAR_DEACTIVE',
}

export interface State {
  menuState: MenuStateEnum;
}

export const NAMESPACE = 'flex';

/* Mutations names */
export const SET_MENU_STATE_MUTATION_NAME = 'setMenuState';

/* Actions names */
export const CHANGE_MENU_STATE_ACTION_NAME = 'changeMenuState';
export const UPDATE_MENU_STATE_ACTION_NAME = 'updateMenuState';
export const SET_MENU_STATE_ACTION_NAME = 'setMenuState';

/* Actions */
export const CHANGE_MENU_STATE_ACTION = `${NAMESPACE}/${CHANGE_MENU_STATE_ACTION_NAME}`;
export const UPDATE_MENU_STATE_ACTION = `${NAMESPACE}/${UPDATE_MENU_STATE_ACTION_NAME}`;
export const SET_MENU_STATE_ACTION = `${NAMESPACE}/${SET_MENU_STATE_ACTION_NAME}`;
