export const SET_CHATS = 'SET_CHATS';
export const SET_CHATS_STATUS = 'SET_CHATS_STATUS';
export const CREATE_CHAT = 'CREATE_CHAT';
export const SET_CHAT_TYPES = 'SET_CHAT_TYPES';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const SET_CHATS_LAST_MESSAGES = 'SET_CHATS_LAST_MESSAGES';

export const SET_INIT_STATUS = 'SET_INIT_STATUS';
